/**
 * Writes the JavaScript entry point for one feature set and prints its path.
 *
 *   node scripts/runtime-entry.mjs deposit   # → build/entry/index.deposit.js
 *
 * The feature sets are the four measurement stages, and each entry registers exactly the
 * surfaces its stage links, so a deposit-only host does not carry the bet slip's code. Both
 * build-jsbundle.sh (iOS) and the Android app's Gradle build call this script, so one list
 * decides what every bundle contains. The file lands under build/ because it is output: a
 * copy kept in the source tree was rewritten by every Android build.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SURFACES = {
  deposit: ['DepositFeature', 'DepositScreen'],
  betslip: ['BetslipFeature', 'BetslipScreen'],
  fighter: ['FighterFeature', 'FighterScreen'],
};

const FEATURE_SETS = {
  runtime: [],
  deposit: ['deposit'],
  both: ['deposit', 'betslip'],
  all: ['deposit', 'betslip', 'fighter'],
};

const set = process.argv[2] ?? 'all';
const features = FEATURE_SETS[set];
if (!features) {
  console.error(
    `error: feature set must be ${Object.keys(FEATURE_SETS).join(', ')} (got '${set}')`,
  );
  process.exit(1);
}

// With no surface to register the entry still has to load React Native, or the
// runtime-only stage would weigh an empty bundle.
const lines = features.length === 0
  ? ["import 'react-native';"]
  : [
    "import { AppRegistry } from 'react-native';",
    "import { feature } from '../../src/runtime/feature';",
    ...features.map((name) => {
      const [, screen] = SURFACES[name];
      return `import { ${screen} } from '../../../${name}/src/${screen}';`;
    }),
    '',
    ...features.map((name) => {
      const [module, screen] = SURFACES[name];
      return `AppRegistry.registerComponent('${module}', feature(${screen}));`;
    }),
  ];

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'build', 'entry', `index.${set}.js`);
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `// Generated by scripts/runtime-entry.mjs — features: ${set}\n${lines.join('\n')}\n`);
console.log(out);
